services:
  - type: web
    name: miku-beam
    env: node
    buildCommand: cd web-client && npm install && npm run build
    startCommand: npm install -g serve && serve -s web-client/dist -l 3000
    staticPublishPath: web-client/dist
    envVars:
      - key: NODE_ENV
        value: production
